[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pydex"
authors = [{name = "Kennedy Putra Kusumo", email = "kennedy.putra.kusumo@gmail.com"}]
dynamic = ["version", "description"]
